name: Test Workflow
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: windows-latest  # Usamos Windows como runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clonar todo el historial para poder hacer `git diff`

      - name: Ensure full history
        run: |
          if (git rev-parse --is-shallow-repository); then
            git fetch --unshallow
          else
            echo "Repository is already complete, skipping unshallow fetch."
          fi

      - name: Debug workspace
        run: dir  # Muestra los archivos en el repositorio para depuración

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Roaming\npm-cache  # Cache en Windows
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Detect new test files
        id: new_tests
        run: |
          # Detectar nuevos archivos .spec.ts o .test.ts en el último commit
          $NEW_TESTS=$(git diff --name-only HEAD~1 HEAD | grep -E '\.spec\.ts$|\.test\.ts$' || echo "")
          if [[ -n "$NEW_TESTS" ]]; then
            echo "New test files de

