name: TDD Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Asegura que se clona todo el historial del repositorio

      - name: Debug workspace
        run: ls -R  # Lista los archivos para verificar la presencia de package.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run tests and capture passed test names
        run: |
          npm test -- --json --outputFile=test-results.json || true
          if [ -f test-results.json ]; then
            PASSED_TESTS=$(jq -r '.testResults[] | select(.status=="passed") | .name' test-results.json)
            if [ -n "$PASSED_TESTS" ]; then
              echo "PASSED_TESTS<<EOF" >> $GITHUB_ENV
              echo "$PASSED_TESTS" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
            fi
          fi

      - name: Commit all passed test results in one commit
        if: env.PASSED_TESTS != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          PASSED_TESTS_COMMIT_MESSAGE="TESTS PASSED: $PASSED_TESTS"
          git commit --allow-empty -m "$PASSED_TESTS_COMMIT_MESSAGE"
          git push

