name: TDD Workflow
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: windows-latest  # Usamos Windows como runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clonar todo el historial para poder hacer `git diff`

      - name: Debug workspace
        run: dir  # Muestra los archivos en el repositorio para depuración

      - name: Ensure full history
        shell: pwsh  # Use PowerShell as the shell
        run: |
          if ((git rev-parse --is-shallow-repository) -eq "true") {
            git fetch --unshallow
          } else {
            Write-Output "Repository is already complete, skipping unshallow fetch."
          }

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Roaming\npm-cache  # Cache en Windows
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./  # Adjust this if `package.json` is in a subdirectory

      - name: Detect new test files
        id: new_tests
        shell: pwsh  # Use PowerShell as the shell
        run: |
          # Detectar nuevos archivos .spec.ts o .test.ts en el último commit
          $NEW_TESTS = git diff --name-only HEAD~1 HEAD | Select-String -Pattern '\.spec\.ts$|\.test\.ts$'
          if ($NEW_TESTS) {
            Write-Output "New test files detected: $NEW_TESTS"
            Write-Output "NEW_TESTS_FOUND=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            Write-Output "NEW_TESTS=$NEW_TESTS" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
            Write-Output "No new test files detected."
            Write-Output "NEW_TESTS_FOUND=false" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }

      - name: Run tests with npm test
        run: |
          npm test -- --json --outputFile=test-results.json || true  # Ejecuta los tests y guarda los resultados

      - name: Check if tests passed
        id: check_tests
        shell: pwsh  # Use PowerShell as the shell
        run: |
          if (Test-Path test-results.json) {
            $PASSED_TESTS = jq -r '.testResults[] | select(.status=="passed") | .name' test-results.json | Join-String -Separator ", "
            if ($PASSED_TESTS) {
              Write-Output "PASSED_TESTS=$PASSED_TESTS" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
              Write-Output "TESTS_PASSED=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            } else {
              Write-Output "No tests passed."
              Write-Output "TESTS_PASSED=false" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            }
          } else {
            Write-Output "No test results found."
            Write-Output "TESTS_PASSED=false" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }

      - name: Commit new test results if npm test passes
        if: env.TESTS_PASSED == 'true' && env.NEW_TESTS_FOUND == 'true'
        shell: pwsh  # Use PowerShell as the shell
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git commit --allow-empty -m "NEW TESTS PASSED: ${{ env.PASSED_TESTS }}"
          git push


